### ISSUE TITLE
Issues of FIFO and MTWR worker

### ISSUE THREAD

**Issue by VivianH61** [prosysscience/JSS#18]
Hi, sorry for bothering you again. Your JSSEnv is very helpful to my final year project, thanks!
Now I want to make comparison of FIFO with other algorithms. However, every time I run FIFO_worker or MTWR_worker, the program just ends up with only 1 episode. I'd appreciate it if you could help me figure it out. Thank you in advance. :)

**Comment by ingambe** [comment]
This is normal because FIFO or MTWR rules are deterministic, so if you run them X times you will always get the same result.
That's why I've run it only once :)

**Comment by VivianH61** [comment]
That explains a lot, thanks!
