### ISSUE TITLE
An error when I try to run it

### ISSUE THREAD

**Issue by DS-cmd** [prosysscience/JSS#21]
When I running the main.py , I get an error like this:

WARNING:tensorflow:From C:\Users\admin\anaconda3\envs\JSS0\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "G:/文献阅读/2021-5/JSS-master/JSS/main.py", line 161, in <module>
    train_func()
  File "G:/文献阅读/2021-5/JSS-master/JSS/main.py", line 104, in train_func
    wandb.init(config=default_config)
  File "C:\Users\admin\anaconda3\envs\JSS0\lib\site-packages\wandb\sdk\wandb_init.py", line 740, in init
    wi.setup(kwargs)
  File "C:\Users\admin\anaconda3\envs\JSS0\lib\site-packages\wandb\sdk\wandb_init.py", line 153, in setup
    wandb_login._login(anonymous=anonymous, force=force, _disable_warning=True)
  File "C:\Users\admin\anaconda3\envs\JSS0\lib\site-packages\wandb\sdk\wandb_login.py", line 210, in _login
    wlogin.prompt_api_key()
  File "C:\Users\admin\anaconda3\envs\JSS0\lib\site-packages\wandb\sdk\wandb_login.py", line 147, in prompt_api_key
    raise UsageError("api_key not configured (no-tty).  Run wandb login")
wandb.errors.error.UsageError: api_key not configured (no-tty).  Run wandb login

Process finished with exit code 1

Do you know how to fix it?
Thanks.

**Comment by ingambe** [comment]
From the stack trace, it seems you got an error because you haven't configured the WandB API.
You need to create a free account on WandB and follow the doc instructions: https://docs.wandb.ai/guides/track/public-api-guide#authentication

**Comment by ingambe** [comment]
This error seems to come from Ray
Ray is not well suited to work with Windows
One way to overcome this would be to run the algorithm inside Windows Linux Subsystem2: https://docs.microsoft.com/en-us/windows/wsl/install-win10
Or a Linux docker container

**Comment by zhaojunqin93** [comment]
Hi there,

I found a similar problem when I run the main.py. I also created an account on WandB and followed the instructions you provided to configure: https://docs.wandb.ai/guides/track/public-api-guide#authentication

The following is the configuration results:
(Virtual) H:\Desktop\JSS>wandb login
wandb: Currently logged in as: zhaojun (use `wandb login --relogin` to force relogin)

But I still got errors, shown below:
H:\Desktop\JSS\Virtual\Scripts\python.exe H:/Desktop/JSS/JSS/main_test.py
WARNING:tensorflow:From H:\Desktop\JSS\Virtual\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_init.py", line 740, in init
    wi.setup(kwargs)
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_init.py", line 80, in setup
    self._wl = wandb_setup._setup()
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 242, in _setup
    wl = _WandbSetup(settings=settings)
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 231, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings)
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 92, in __init__
    self._settings_setup(settings, self._early_logger)
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 118, in _settings_setup
    s._infer_run_settings_from_env(_logger=early_logger)
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_settings.py", line 849, in _infer_run_settings_from_env
    program, _logger=_logger
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_settings.py", line 138, in _get_program_relpath_from_gitrepo
    root, os.path.relpath(os.getcwd(), root), program
  File "C:\Users\zqin794.UOA\AppData\Local\Programs\Python\Python37\lib\ntpath.py", line 564, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'H:', start on mount '\\\\files.auckland.ac.nz\\myhome'
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_init.py", line 740, in init
    wi.setup(kwargs)
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_init.py", line 80, in setup
    self._wl = wandb_setup._setup()
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 242, in _setup
    wl = _WandbSetup(settings=settings)
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 231, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings)
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 92, in __init__
    self._settings_setup(settings, self._early_logger)
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 118, in _settings_setup
    s._infer_run_settings_from_env(_logger=early_logger)
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_settings.py", line 849, in _infer_run_settings_from_env
    program, _logger=_logger
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_settings.py", line 138, in _get_program_relpath_from_gitrepo
    root, os.path.relpath(os.getcwd(), root), program
  File "C:\Users\zqin794.UOA\AppData\Local\Programs\Python\Python37\lib\ntpath.py", line 564, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'H:', start on mount '\\\\files.auckland.ac.nz\\myhome'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:/Desktop/JSS/JSS/main_test.py", line 219, in <module>
    train_func()
  File "H:/Desktop/JSS/JSS/main_test.py", line 162, in train_func
    wandb.init(config=default_config)
  File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_init.py", line 780, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem

Process finished with exit code 1

I would really appreciate that if you can inlight me. Looking forward to your reply.

Cheers!

**Comment by zhaojunqin93** [comment]
> Hi there,
> 
> I found a similar problem when I run the main.py. I also created an account on WandB and followed the instructions you provided to configure: https://docs.wandb.ai/guides/track/public-api-guide#authentication
> 
> The following is the configuration results:
> (Virtual) H:\Desktop\JSS>wandb login
> wandb: Currently logged in as: zhaojun (use `wandb login --relogin` to force relogin)
> 
> But I still got errors, shown below:
> H:\Desktop\JSS\Virtual\Scripts\python.exe H:/Desktop/JSS/JSS/main_test.py
> WARNING:tensorflow:From H:\Desktop\JSS\Virtual\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
> Instructions for updating:
> non-resource variables are not supported in the long term
> Traceback (most recent call last):
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_init.py", line 740, in init
> wi.setup(kwargs)
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_init.py", line 80, in setup
> self._wl = wandb_setup._setup()
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 242, in _setup
> wl = _WandbSetup(settings=settings)
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 231, in **init**
> _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings)
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 92, in **init**
> self._settings_setup(settings, self._early_logger)
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 118, in _settings_setup
> s._infer_run_settings_from_env(_logger=early_logger)
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_settings.py", line 849, in _infer_run_settings_from_env
> program, _logger=_logger
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_settings.py", line 138, in _get_program_relpath_from_gitrepo
> root, os.path.relpath(os.getcwd(), root), program
> File "C:\Users\zqin794.UOA\AppData\Local\Programs\Python\Python37\lib\ntpath.py", line 564, in relpath
> path_drive, start_drive))
> ValueError: path is on mount 'H:', start on mount '\\files.auckland.ac.nz\myhome'
> wandb: ERROR Abnormal program exit
> Traceback (most recent call last):
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_init.py", line 740, in init
> wi.setup(kwargs)
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_init.py", line 80, in setup
> self._wl = wandb_setup._setup()
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 242, in _setup
> wl = _WandbSetup(settings=settings)
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 231, in **init**
> _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings)
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 92, in **init**
> self._settings_setup(settings, self._early_logger)
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_setup.py", line 118, in _settings_setup
> s._infer_run_settings_from_env(_logger=early_logger)
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_settings.py", line 849, in _infer_run_settings_from_env
> program, _logger=_logger
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_settings.py", line 138, in _get_program_relpath_from_gitrepo
> root, os.path.relpath(os.getcwd(), root), program
> File "C:\Users\zqin794.UOA\AppData\Local\Programs\Python\Python37\lib\ntpath.py", line 564, in relpath
> path_drive, start_drive))
> ValueError: path is on mount 'H:', start on mount '\\files.auckland.ac.nz\myhome'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "H:/Desktop/JSS/JSS/main_test.py", line 219, in
> train_func()
> File "H:/Desktop/JSS/JSS/main_test.py", line 162, in train_func
> wandb.init(config=default_config)
> File "H:\Desktop\JSS\Virtual\lib\site-packages\wandb\sdk\wandb_init.py", line 780, in init
> six.raise_from(Exception("problem"), error_seen)
> File "", line 3, in raise_from
> Exception: problem
> 
> Process finished with exit code 1
> 
> I would really appreciate that if you can inlight me. Looking forward to your reply.
> 
> Cheers!

Hi there,

The error above has been solved. But I encounter another problem. The link of Ray dashboard does not work.

D:\JSS_JSSEnv\JSS\venv\Scripts\python.exe D:/JSS_JSSEnv/JSS/JSS/main.py
WARNING:tensorflow:From D:\JSS_JSSEnv\JSS\venv\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
wandb: Currently logged in as: zhaojun (use `wandb login --relogin` to force relogin)
wandb: Tracking run with wandb version 0.10.30
wandb: Syncing run lucky-snowflake-3
wandb:  View project at https://wandb.ai/zhaojun/JSS-JSS
wandb:  View run at https://wandb.ai/zhaojun/JSS-JSS/runs/1cb8k71c
wandb: Run data is saved locally in D:\JSS_JSSEnv\JSS\JSS\wandb\run-20210527_164314-1cb8k71c
wandb: Run `wandb offline` to turn off syncing.

2021-05-27 16:43:24,893	INFO services.py:1173 -- View the Ray dashboard at http://127.0.0.1:8265

Process finished with exit code -1

I would really appreciate that if you can inlight me. Looking forward to your reply.

Cheers!

**Comment by DS-cmd** [comment]
Sorry! I haven't encountered this kind of problem, so I don't know how to solve it.
You should make sure that you have configured the correct environment in linux.

**Comment by ingambe** [comment]
From multiple reports, it seems that the Ray dependency we use has some difficulties with Windows
I would recommend using a Linux distribution, or, if not possible, executing the program through [Windows Linux Subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10) 

I've added a message in the Readme about this issue.
Thanks :)
